### ISSUE TITLE
JS Options use dashes, not underscores.

### ISSUE THREAD

**Issue by jmbarne3** [UCF/UCF-Header-Plugin#1]
The two options provided by the plugin use dashes, and not underscores: https://github.com/UCF/UCF-Header-Plugin/blob/master/includes/header_common.php#L15-L16.

I.e. `use_1200_breakpoint` should be `use-1200-breakpoint`.

**Comment by vinhtvu2** [comment]
Issue will be resolved in v1.0.1 release.
https://github.com/UCF/UCF-Header-Plugin/commit/82d614b91ffe67d358ab41035a4bde59f1a1a2f6
